#!/usr/bin/env python3.10
"""
Generate All Female Voices with PocketTTS
==========================================
This script generates audio samples for all available female voices in PocketTTS.

Usage:
    python3.10 generate_female_voices.py
    python3.10 generate_female_voices.py --text "Custom text to speak"
    python3.10 generate_female_voices.py --output-dir ./female_voices
"""

import os
import sys
import argparse
from pathlib import Path

try:
    from pocket_tts import TTSModel
    import scipy.io.wavfile
    import torch
except ImportError as e:
    print(f"❌ Error: Required package not installed - {e}")
    print("Install with: pip install pocket-tts scipy torch")
    sys.exit(1)


# All female voices available in PocketTTS
# Based on https://huggingface.co/kyutai/pocket-tts
FEMALE_VOICES = [
    "alba",      # Female voice
    "fantine",   # Female voice
    "cosette",   # Female voice
    "eponine",   # Female voice
    "azelma",    # Female voice
]

# Male voices (for reference, not used)
MALE_VOICES = [
    "marius",    # Male voice
    "javert",    # Male voice
    "jean",      # Male voice
]


def generate_female_voices(text, output_dir):
    """Generate audio for all female voices"""
    
    # Create output directory
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    print(f"🎤 Generating Female Voices with PocketTTS")
    print(f"📝 Text: \"{text}\"")
    print(f"📁 Output: {output_dir}")
    print(f"🔢 Total voices: {len(FEMALE_VOICES)}")
    print("=" * 60)
    print()
    
    # Load the TTS model once (this is slow, so we do it once)
    print("Loading TTS model... (this may take a moment)")
    try:
        tts_model = TTSModel.load_model()
        print(f"✓ Model loaded (sample rate: {tts_model.sample_rate} Hz)")
        print()
    except Exception as e:
        print(f"❌ Failed to load model: {e}")
        return
    
    successful = 0
    failed = []
    
    for idx, voice in enumerate(FEMALE_VOICES, 1):
        try:
            print(f"[{idx}/{len(FEMALE_VOICES)}] Generating: {voice}...", end=" ", flush=True)
            
            # Get voice state for this voice
            voice_state = tts_model.get_state_for_audio_prompt(voice)
            
            # Generate audio
            audio = tts_model.generate_audio(voice_state, text)
            
            # Save to file
            filename = f"{voice}.wav"
            output_file = output_path / filename
            
            # Write audio data (audio is a 1D torch tensor containing PCM data)
            scipy.io.wavfile.write(str(output_file), tts_model.sample_rate, audio.numpy())
            
            print(f"✓ Saved to {filename}")
            successful += 1
            
        except Exception as e:
            print(f"✗ Failed: {str(e)}")
            failed.append((voice, str(e)))
    
    print()
    print("=" * 60)
    print(f"✅ Successfully generated: {successful}/{len(FEMALE_VOICES)}")
    
    if failed:
        print(f"❌ Failed: {len(failed)}")
        print("\nFailed voices:")
        for voice, error in failed:
            print(f"  - {voice}: {error}")
    
    print(f"\n📁 All files saved to: {output_dir}")


def list_all_voices():
    """List all available voices in PocketTTS"""
    print("🎤 Available PocketTTS Voices")
    print("=" * 60)
    print()
    print("👩 FEMALE VOICES:")
    for voice in FEMALE_VOICES:
        print(f"   • {voice}")
    print()
    print("👨 MALE VOICES (not generated by this script):")
    for voice in MALE_VOICES:
        print(f"   • {voice}")
    print()
    print("=" * 60)
    print(f"Total: {len(FEMALE_VOICES)} female voices, {len(MALE_VOICES)} male voices")
    print()
    print("Note: You can also use custom voice files or HuggingFace voice URLs")
    print("Example: './my_voice.wav' or 'hf://kyutai/tts-voices/...')")


def main():
    parser = argparse.ArgumentParser(
        description="Generate audio samples for all female voices in PocketTTS",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 generate_female_voices.py
  python3 generate_female_voices.py --text "Hello, I am Miko!"
  python3 generate_female_voices.py --output-dir ./my_voices
  python3 generate_female_voices.py --list-voices
        """
    )
    
    parser.add_argument(
        '--text',
        type=str,
        default="Hello! This is a sample of my voice. I hope you enjoy listening to this demonstration.",
        help='Text to synthesize (default: sample text)'
    )
    
    parser.add_argument(
        '--output-dir',
        type=str,
        default='./female_voices_output',
        help='Output directory for audio files (default: ./female_voices_output)'
    )
    
    parser.add_argument(
        '--list-voices',
        action='store_true',
        help='List all available voices and exit'
    )
    
    args = parser.parse_args()
    
    if args.list_voices:
        list_all_voices()
        return
    
    generate_female_voices(args.text, args.output_dir)


if __name__ == "__main__":
    main()
